apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-name
  labels:
    failure-domain.beta.kubernetes.io./zone: us-central-a__us-entral1-b
spec: 
  capacity:
    storage: 400Gi
  accessMode: 
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4